# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Black Bar Labs | iOS Development and Consulting
short-title: Black Bar Labs
email      : info@blackbarlabs.com #this is also the email contact forms will go to
description: "My name is Joel Perry and I have been developing for Apple platforms since 2014, creating mobile apps in the music, streaming, B2B, and B2C spaces. I build iOS apps using the most modern technologies available, focusing on a delightful experience for users and the business vision of my clients."
author     : Black Bar Labs
logo-image-path: assets/img/logo.png
# logo:     #optional, defaults to site title
#   path: assets/img/logo.png
#   height: 90 #height in px, defaults to 52px

analytics:
  google: G-20VNS9DY1M

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/xeojwpqr"